### ISSUE TITLE
Cannot read property 'data' of undefined

### ISSUE THREAD

**Issue by PasimkNemokamai2017** [Tegos/travian-elephant-finder#3]
Hey, I tried to run this awesome script and I got this error.

> Unhandled rejection TypeError: Cannot read property 'data' of undefined
    at makeSearchElephant.then (C:\Users\Desktop\travian-master\app.js:49:26)
    at tryCatcher (C:\Users\Desktop\travian-master\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Desktop\travian-master\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\Desktop\travian-master\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Users\Desktop\travian-master\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\Desktop\travian-master\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (C:\Users\Desktop\travian-master\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\Desktop\travian-master\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\Desktop\travian-master\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at module.exports.runLoopOnce (C:\Users\Desktop\travian-master\node_modules\deasync\index.js:65:10)
    at module.exports (C:\Users\Desktop\travian-master\node_modules\deasync-promise\index.js:13:9)
    at module.exports.interval (C:\Users\Desktop\travian-master\node_modules\system-sleep\module.js:24:36)
    at Object.<anonymous> (C:\Users\Desktop\travian-master\app.js:74:3)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)

Second question does this work on Travian 4.x servers? because I change some lines like "travianServer", I change from Ajax to karte.php because 4.x server don't have Ajax. And last question will be. What I need to change in Config file? Cookie and Ajaxtoken, what is it? And how to get it? Sometimes when I launch script its showing 404.
`return rp.post(
		travianServer + '/karte.php?cmd=viewTileDetails',
		{`

**Comment by PasimkNemokamai2017** [comment]
If I change only server line on Config file, I got this error: 

> Unhandled rejection TypeError: Cannot read property 'parent' of undefined
    at Function.exports.update (C:\Users\Desktop\travian-elephant-master\node_modules\cheerio\lib\parse.js:69:26)
    at module.exports (C:\Users\Desktop\travian-elephant-master\node_modules\cheerio\lib\parse.js:19:11)
    at Function.exports.load (C:\Users\Desktop\travian-elephant-master\node_modules\cheerio\lib\static.js:27:14)
    at makeSearchElephant.then (C:\Users\Desktop\travian-elephant-master\app.js:52:22)
    at tryCatcher (C:\Users\Desktop\travian-elephant-master\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Desktop\travian-elephant-master\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\Desktop\travian-elephant-master\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Users\Desktop\travian-elephant-master\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\Desktop\travian-elephant-master\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (C:\Users\Desktop\travian-elephant-master\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\Desktop\travian-elephant-master\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\Desktop\travian-elephant-master\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at module.exports.runLoopOnce (C:\Users\Desktop\travian-elephant-master\node_modules\deasync\index.js:65:10)
    at module.exports (C:\Users\Desktop\travian-elephant-master\node_modules\deasync-promise\index.js:13:9)
    at module.exports.interval (C:\Users\Desktop\travian-elephant-master\node_modules\system-sleep\module.js:24:36)
    at Object.<anonymous> (C:\Users\Desktop\travian-elephant-master\app.js:74:3)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)

**Comment by Tegos** [comment]
Hello. Sorry for long answer.  Check updated readme file.
